--매칭, 매칭후기, 매칭참여유저정보

DROP TABLE MATCHING;
DROP TABLE MATCHING_LATE;
DROP TABLE MATCHING_INFO;

DROP SEQUENCE SEQ_MATCHING;



CREATE TABLE MATCHING(
    MATCHING_CODE NUMBER,
    MATCHING_RESULT VARCHAR2(1) DEFAULT 'N' CHECK(MATCHING_RESULT IN ('Y','N')),
    MATCHING_DATE DATE DEFAULT SYSDATE,
    UNMATCHING_DATE DATE DEFAULT SYSDATE, 
    MATCHINGTEXT_POSTSEQ NUMBER, 
    CHATROOM_NUMBER NUMBER
);


CREATE TABLE MATCHING_LATE(
    ANOTHER_ID VARCHAR2(50) NOT NULL,
    ANOTHER_SCORE CHAR(10) DEFAULT 0 CHECK(ANOTHER_SCORE IN (1,2,3,4,5,6,7,8,9,10)),
    REVIEW_PHOTO VARCHAR2(300) NOT NULL,
    REVIEW_DESC VARCHAR2(3000),
    LATE_URL VARCHAR2(300) NOT NULL,
    MATCHING_CODE NUMBER,
    LATE_ID VARCHAR2(50) NOT NULL
);

CREATE TABLE MATCHING_INFO(
     MATCHING_CODE NUMBER,
     MATCHING_TRY VARCHAR2(1) DEFAULT 'N' CHECK(MATCHING_TRY IN ('Y','N')),
     MATCHING_GOAL VARCHAR2(1) DEFAULT 'N' CHECK(MATCHING_GOAL IN ('Y','N')),
     MATCHING_ID VARCHAR(50) NOT NULL
);





CREATE SEQUENCE SEQ_MATCHING;



ALTER TABLE MATCHING ADD CONSTRAINT MATCHING_CODE_PK PRIMARY KEY(MATCHING_CODE);




ALTER TABLE MATCHING ADD CONSTRAINT MATCHING_CHATROOM_NUMBER_FK FOREIGN KEY(CHATROOM_NUMBER) REFERENCES CHAT;             -- 채팅 테이블(준영) 필요
ALTER TABLE MATCHING ADD CONSTRAINT MATCHING_MATCHINGTEXT_POSTSEQ_FK FOREIGN KEY(MATCHINGTEXT_POSTSEQ) REFERENCES MATCHINGTEXT;  -- 매칭글 테이블(준영) 필요
ALTER TABLE MATCHING_LATE ADD CONSTRAINT MATCHING_LATE_MATCHING_CODE_FK FOREIGN KEY(MATCHING_CODE) REFERENCES MATCHING;
-- ALTER TABLE MATCHING_LATE ADD CONSTRAINT MATCHING_LATE_유저정보 아이디_FK FOREIGN KEY(유저정보 아이디) REFERENCES USER_INFO; 유저정보(민수) 아이디쪽이랑 맞춰야함
ALTER TABLE MATCHING_INFO ADD CONSTRAINT MATCHING_INFO_MATCHING_CODE_FK FOREIGN KEY(MATCHING_CODE) REFERENCES MATCHING;



